// Chapter 3 content. Prose and exhibits; build_chapter.js does formatting.
// Register per Book_language_and_style_guide.md.

module.exports = [

["h1", "3  Building the Propensity Score Analysis"],

["h2", "3.1  Purpose and scope of this chapter"],

["p", "Chapter 2 produced an analysis file: one row per person, covariates dated 2016 or earlier, a treatment flag, an eligibility flag, and an outcome that must not be examined until Chapter 9. This chapter fits a model to that file and produces a propensity score, which is the single number that every method in Chapters 4 to 7 operates on."],

["p", "The chapter has one argument, and it runs against the instinct most analysts bring to the task. A propensity score model is not a prediction model, and the habits that produce a good prediction model produce a worse propensity score. We will fit six specifications to the same data, rank them by how well they predict treatment, and then score each one against the known treatment effect. The two rankings disagree, and they disagree in a way that would mislead a researcher who had only the first of them."],

["p", "By the end of the chapter, readers should be able to specify a propensity score model from a declared covariate set, estimate it by logistic regression and by gradient boosting, read the output without over-reading it, quantify what a near-instrument costs, and produce the diagnostics that Chapter 4 needs in order to decide what to trim. Readers will also have measured, rather than assumed, the difference between a model that predicts well and a model that removes selection bias."],

["p", "One matter of scope. This chapter estimates the score and stops. It does not match, weight, stratify or estimate any treatment effect for its own sake; where an effect is reported here, it is the ATT and it is reported only as a way of scoring a specification, and the estimator used is the plain 1:1 nearest-neighbour match that Chapter 5 sets out properly. The outcome is used in this chapter solely to tell the reader which specification was right, which is a luxury of a simulated dataset and is not available in any real project."],

["h2", "3.2  What the propensity score is"],
["h3", "3.2.1  The score as a balancing score"],

["p", "The propensity score is the probability that a person receives the treatment, given their observed covariates. It is a single number between 0 and 1, and in PLIDA-SIM it is the modelled probability that a person commenced the Employment Pathways Programme in 2017, given everything recorded about them in 2016 or earlier."],

["p", "The property that makes the score useful is not that it predicts treatment. It is that, conditional on the score, the observed covariates are independent of treatment assignment. Two persons with the same propensity score may differ in age, education and payment history, but among all persons who share a score, the distribution of those covariates is the same in the treated and control conditions. A score with this property is called a balancing score, and it is what allows a comparison conditioned on one number to substitute for a comparison conditioned on eighteen."],

["p", "An analogy may help, provided it is not pushed too far. In a randomised trial every participant has the same probability of assignment, commonly one half, and that single shared number is why the conditions are comparable: knowing a person's assignment probability tells us nothing about them, so the two groups differ only by chance. In an observational study the assignment probability varies from person to person, and it usually varies systematically with the characteristics (e.g., education, prior earnings, health) that also determine the outcome. The propensity score recovers that varying probability, and comparing persons who share a value of it reconstructs, within that stratum, the situation a trial would have created by design."],

["p", "This is worth stating carefully, because it is the whole justification for the method and it is conditional on something that is usually false. The balancing property holds for the true propensity score, which is the one generated by the actual assignment mechanism. What we fit is an estimate, and our estimate balances the covariates only to the extent that the model is correctly specified. Chapter 8 is devoted to checking whether the balance we hoped for actually arrived; this chapter is about giving it the best chance."],

["p", "It follows that the objective of the model is balance, not accuracy. These two things are often confused because both are served by including the covariates that drive selection, and for that reason a better propensity model usually does predict better up to a point. The confusion becomes damaging past that point, and Section 3.5 shows where the point is."],
["h3", "3.2.2  Why prediction is not the objective"],

["p", "Suppose a propensity model predicted treatment perfectly, assigning a score of 1 to every participant and 0 to every non-participant. It would have an area under the ROC curve of 1.0, which is the best achievable value, and it would be entirely useless. No treated person would have a comparable control, no match would be possible, every inverse probability weight would be infinite, and the analysis would stop. Perfect prediction is not merely unhelpful; it is the failure mode."],

["p", "Chapter 2 encountered exactly this with referral_type, a variable recorded only for participants, which predicts treatment perfectly and separates any model containing it. That case is obvious once seen. The same mechanism operates in milder form whenever a covariate predicts treatment strongly without affecting the outcome, and in that milder form it is not obvious at all, because the model converges, the diagnostics look healthy, and the score appears more discriminating than before."],

["p", "The useful way to hold this is that a propensity model is trying to describe the assignment mechanism, not to forecast it. A covariate generally belongs in the model because it is a reason the two conditions differ in ways that also matter for the outcome, which is the definition of a confounder from Section 2.4. A covariate that improves prediction without being a confounder adds variance and removes no bias, and Section 3.7 measures how much variance."],

["p", "Predictive performance nonetheless has one legitimate use in this setting, which is as a lower bound. A model with an area under the curve close to 0.5 has found almost nothing, and if the programme's own operating logic says that caseworkers select on characteristics recorded in the data, a score that cannot discriminate at all may suggest that the covariates are wrong or that the file is broken. Specification 1 in Section 3.5 is an example. Beyond that floor, the statistic stops being informative, and past a certain point it becomes actively misleading."],

["h2", "3.3  Specifying the model"],
["h3", "3.3.1  The covariate set carried from Chapter 2"],

["p", "Nothing in this chapter chooses covariates. Section 2.4 chose them, from the programme's operating logic rather than from the data, and recorded the choice as three named lists before any model was fitted. We use those lists here, and the discipline of not revisiting them is part of the method: a covariate set that is adjusted after seeing what the model does is a covariate set selected on the outcome."],

["p", "Table 3.1 sets out what enters the propensity model and what we hold back. Eighteen columns enter, drawn from the confounder list. The pure outcome predictor, occupation_group, is held back for Chapter 6, for the reason established in Section 2.4.2: it improves precision only in a model of the outcome, and in the propensity model it slightly loosens the estimate. The near-instrument, mutual_obligation_status, is held back so that Section 3.7 can measure what including it would have cost."],

["tab", "3.1", "What enters the propensity model, and what is held back.",
  [2600, 1500, 4926],
  ["Covariate", "Role", "Form entering the model"],
  [
    ["age_2016", "Confounder", "Level"],
    ["sex", "Confounder", "Binary indicator"],
    ["dependent_children", "Confounder", "Count, median imputed"],
    ["highest_edu", "Confounder", "Ordinal, 0 to 4"],
    ["remoteness_area", "Confounder", "Ordinal, 0 to 3"],
    ["seifa_irsd_decile", "Confounder", "Decile, 1 to 10"],
    ["fortnights", "Confounder", "Count, 0 to 26"],
    ["lts (fortnights \u2265 20)", "Confounder", "Binary persistence indicator"],
    ["gp_attendances", "Confounder", "Count"],
    ["mh_item_flag", "Confounder", "Binary"],
    ["earnings_2014, 2015, 2016", "Confounder", "log(1 + x), three separate columns"],
    ["earnings_drop_2016", "Confounder", "Proportional fall, 2015 to 2016"],
    ["missingness indicators", "Confounder", "Four binary flags, per Section 2.7.6"],
    ["occupation_group", "Pure outcome predictor", "Held back; enters in Chapter 6"],
    ["mutual_obligation_status", "Near-instrument", "Held back; see Section 3.7"],
    ["referral_type", "Post-treatment", "Excluded; see Section 2.4.4"],
  ],
  "Eighteen numeric columns enter the model once the ordinal and indicator forms are counted. The final three rows are in the analysis file and are deliberately not used here.",
  ["l", "l", "l"]
],

["p", "Two features of that list deserve comment. Fragment 3.1 restates Chapter 2's declaration in the column names of the analysis file and adds the covariates that Section 2.6 derived from the earnings and payment histories (earnings_2014, earnings_drop_2016 and lts, a single-year proxy for the persistence indicator of Section 2.6.3), together with sex; none of the additions was chosen on the evidence of a fitted model. The first is that all three pre-treatment years of earnings enter separately, as Section 2.6.1 promised they would. A single year would discard the trajectory, and the trajectory carries information about selection that the level does not; a person earning $30,000 after three years at that level is not in the same position as one who earned $60,000 two years earlier."],

["frag", [
  "CONFOUNDERS = [                      # declared in Chapter 2, not chosen here",
  "    \"age_2016\", \"sex\", \"dependent_children\", \"highest_edu\",",
  "    \"remoteness_area\", \"seifa_irsd_decile\", \"fortnights\", \"lts\",",
  "    \"gp_attendances\", \"mh_item_flag\",",
  "    \"earnings_2014\", \"earnings_2015\", \"earnings_2016\", \"earnings_drop_2016\",",
  "]",
  "HELD_BACK = [\"occupation_group\",           # outcome predictor, Chapter 6",
  "             \"mutual_obligation_status\"]   # near-instrument, Section 3.7",
], "Fragment 3.1  The covariate sets, restated rather than reselected. Full script: ch03/03_01_covariate_sets.py"],

["p", "The second is that the missingness indicators constructed in Section 2.7 enter the propensity model as covariates in their own right. This follows from the argument there: under a missing-not-at-random mechanism the fact of non-response is one of the few observable traces of the mechanism, and discarding it discards information about who was selected."],
["h3", "3.3.2  Choosing a functional form"],

["p", "Having fixed which covariates enter, we are left with decisions about the form in which each one enters. Three of these arise in almost every application, and the analysis file has already settled two of them."],

["p", "Continuous money variables enter as logarithms, specifically as log(1 + x) so that zero earnings remain defined (i.e., so that a person who earned nothing is not dropped). The reason is that the effect of an extra thousand dollars on the probability of commencing is plainly larger at $5,000 than at $80,000, and a linear term cannot express that. The log transform imposes a constant proportional effect instead, which is a strong assumption and usually a better one. It is nonetheless an assumption about the assignment mechanism, and it can be checked: Section 10.2.1 shows that in PLIDA-SIM a term in 2016 earnings in dollars also belongs in the model, that a likelihood-ratio test would have detected it in most draws, and that leaving it out, together with a squared term in age, accounts for about three points of the bias that the later chapters report."],

["p", "Ordinal covariates (e.g., education and remoteness) generally enter as scores rather than as sets of dummy variables. This imposes equal spacing between adjacent levels, which is not exactly right, and it buys a substantial reduction in the number of parameters. Where a reader prefers dummies, Exercise 3.2 asks them to refit with dummies and compare, and the answer in these data is that it makes very little difference; the loss from the equal-spacing assumption is small relative to the draw-to-draw variability of everything else."],

["p", "Counts such as fortnights on payment and GP attendances enter as levels. Fortnights additionally enters as the binary persistence indicator lts, because Section 2.6.3 established that the distinction between a short spell and a full year is the distinction caseworkers act on, and a linear count term cannot represent a threshold."],
["h3", "3.3.3  Higher-order terms and interactions"],

["p", "The natural next question is whether to add squared terms and interactions. The argument for doing so is that the true assignment mechanism is unlikely to be exactly linear in the log odds, and that the propensity model is a nuisance model whose only job is to balance, so there is no cost to flexibility and no reason for parsimony."],

["p", "That argument is sound in principle and worth testing rather than accepting. Specification 4 in Table 3.3 adds a squared term in fortnights, an interaction between fortnights and the persistence indicator, and an interaction between 2016 earnings and education. The three terms move the area under the curve from 0.675 to 0.676 and the matched bias from \u221212.5 to \u22126.5 per cent, with the draw-to-draw standard deviation rising from 7.6 to 8.4."],

["p", "The honest reading is that the added terms did nothing detectable. The bias moved by six percentage points in the favourable direction, which sounds worth having until it is set against a standard deviation of 8.4 across draws; the movement is smaller than the spread, and a second set of five draws could as easily show it going the other way. That is not an argument against flexibility in general; it is an observation that in these data the recoverable structure is close to linear in the log odds, and that adding terms on the theory that they might help has a cost in variance that is easier to measure than the benefit. Chapter 8 returns to this question from the other end, by testing whether the interactions balance after matching, which is the check that would actually justify including them."],
["h3", "3.3.4  Transforms that make no difference, and why"],

["p", "It is worth knowing which specification decisions do not matter, partly to save effort and partly because a decision that cannot change the answer should not be presented in a report as though it were a judgement call."],

["p", "Deflation is the clearest case. Chapter 2 insisted, at some length, that monetary variables be converted to constant 2019 dollars before use, and Section 2.6.5 gave the reasons. Those reasons concern the outcome and any comparison across years. They do not extend to the propensity model. Refitting the model on nominal rather than deflated earnings changes the fitted score by 0.000000 on average and by 0.000001 at the largest, leaves the area under the curve identical at 0.6705, and leaves every matched pair unchanged."],

["p", "The explanation is worth a sentence, because it generalises. Each year of earnings enters as its own column, and deflation multiplies a whole column by a constant; under the logarithm that constant becomes an additive shift, which the model absorbs into the coefficient and the intercept without changing any fitted value. A transform that is constant within a covariate cannot change a linear model's predictions. This would not hold if the model pooled years into a single income variable, and it would not hold for a tree-based model, which splits on raw values."],
["h3", "3.3.5  Which persons the model is fitted on"],

["p", "One specification decision remains, and it is the one most often made by default. Chapter 2 constructed an eligibility flag, and 42,575 of the 50,000 persons satisfy it. The propensity model can be fitted to everyone or to the eligible subset, and the two are not equivalent."],

["p", "The case for restricting is that the 7,425 ineligible persons were never candidates for referral, so including them asks the model to describe an assignment mechanism that did not operate on them. The case against is that 502 actual participants fall outside the eligibility rule, as Section 2.2.4 recorded, so restricting discards real treated cases."],

["p", "Fitted both ways across five draws, the difference is not one of performance. The area under the curve moves from 0.678 to 0.675, the score range is unchanged to two decimal places, the largest stabilised weight is 4.3 either way, and the matched bias moves from \u22129.0 to \u221212.5 per cent with the draw-to-draw standard deviation rising from 5.0 to 7.6. The two intervals overlap comfortably and neither specification is detectably better than the other."],

["p", "What the choice does determine is the estimand, which is another appearance in this book of the pattern Section 2.5.2 named. Restricting the model to the eligible population produces an estimate about eligible participants; fitting to everyone produces an estimate about all participants, including the 502 the eligibility rule does not describe. Neither is wrong, and a report that does not say which was done cannot be interpreted. We fit the model to the eligible population, consistently with the eligibility flag being applied once in Chapter 2 and never reapplied, and readers who refit the model on all persons can quantify the difference directly."],

["frag", [
  "elig = analysis[analysis[\"eligible\"] == 1]     # 42,575 of 50,000",
  "",
  "# The flag was computed once, in Chapter 2, and is not recomputed here.",
  "# Recomputing an eligibility rule in each script is how two tables in",
  "# the same report come to describe different populations.",
  "ps = fit_propensity(design_matrix(elig), elig[\"treated\"])",
], "Fragment 3.2  Restricting the model to the eligible population. Full script: ch03/03_02_estimate_logit.py"],

["box", "In the DataLab: the model you can fit is not always the model you want", [
  "Propensity models in the DataLab are fitted under two constraints that do not apply outside it. Output is cleared before release, so a coefficient table cannot generally leave the environment unless it has been checked against the disclosure rules, and small cells in categorical covariates are a common reason for a table to be refused.",
  "The practical consequence is to prefer ordinal scores and continuous forms over long sets of dummy variables wherever the substantive loss is small. A remoteness score with four levels raises no disclosure question; a set of sa4 dummies with several hundred levels almost certainly will, and the model is no better for them.",
]],

["h2", "3.4  Estimating the score with logistic regression"],
["h3", "3.4.1  Fitting the model"],

["p", "With the covariate set and the functional forms settled, the estimation itself is unremarkable. The model is a logistic regression of the treatment indicator on the eighteen covariates, fitted on the 42,575 persons of the eligible population. Covariates are standardised before fitting, which changes nothing about the fitted probabilities but makes the coefficients comparable with one another."],

["frag", [
  "X = design_matrix(analysis)          # the eighteen columns of Table 3.1",
  "Z = (X - X.mean()) / X.std()         # standardise, for readable coefficients",
  "",
  "model = LogisticRegression(max_iter=5000, C=1e6).fit(Z, analysis[\"treated\"])",
  "analysis[\"ps_logit\"] = model.predict_proba(Z)[:, 1]",
], "Fragment 3.3  Estimating the propensity score. Full script: ch03/03_02_estimate_logit.py"],

["p", "The large value of C disables the regularisation that scikit-learn applies by default. This matters more than it appears. Regularisation shrinks coefficients towards zero, which is desirable when the objective is prediction on new data and undesirable here, because a shrunken coefficient on a confounder means that confounder is under-adjusted. The default in most software is to regularise; the default appropriate to this task is not to."],

["p", "Two things should be checked at this point, and both take one line. The first is that the optimiser converged; scikit-learn warns when it does not, and a model that has hit its iteration limit has coefficients that mean nothing. The second is that no fitted probability is numerically 0 or 1, which is the signature of the separation problem that Section 2.4.4 described. Neither check is a guarantee of anything, and a model can converge cleanly on a specification that is substantively wrong, which is the subject of the next three sections."],

["p", "The fitted score on the primary dataset runs from 0.022 to 0.573, with a mean of 0.1143 against an observed participation rate of 0.1143. That the two agree to four decimal places is a property of the maximum likelihood fit rather than a diagnostic result, and it should not be read as evidence that the model is any good, since any logistic regression with an intercept reproduces the observed rate exactly (Table 3.6)."],
["h3", "3.4.2  Reading the output, and what not to read into it"],

["p", "Table 3.2 reports the eight largest standardised coefficients. It is included because readers will look at such a table, and because most of what they will be tempted to conclude from it is wrong."],

["tab", "3.2", "Standardised logistic coefficients, eight largest in absolute value.",
  [2700, 1500, 1300, 1300, 2226],
  ["Covariate", "Coefficient", "Std. error", "z", "Direction"],
  [
    ["remoteness_area", "+0.270", "0.014", "19.4", "More remote, more likely to commence"],
    ["log earnings 2016", "\u22120.175", "0.042", "\u22124.1", "Higher earnings, less likely"],
    ["fortnights on payment", "+0.166", "0.030", "5.6", "Longer on payment, more likely"],
    ["age_2016", "\u22120.152", "0.016", "\u22129.4", "Older, less likely"],
    ["highest_edu", "\u22120.131", "0.018", "\u22127.4", "More educated, less likely"],
    ["seifa_irsd_decile", "\u22120.116", "0.017", "\u22126.9", "Less disadvantaged area, less likely"],
    ["mh_item_flag", "+0.114", "0.014", "8.3", "Mental health contact, more likely"],
    ["lts (long-term recipient)", "+0.079", "0.028", "2.9", "Entrenched spell, more likely"],
  ],
  "Primary dataset, seed 20260808, eligible population (n = 42,575). Covariates standardised, so coefficients are comparable in magnitude. Intercept \u22122.188; area under the curve 0.670 on this draw.",
  ["l", "r", "r", "r", "l"]
],

["p", "The signs are all in the direction the programme's operating logic predicts, which is a genuine if weak check: a model in which higher education raised the probability of commencing an employment programme would suggest an error upstream, most likely a reversed ordinal scale of the kind Section 2.9.1 warns about."],

["p", "Beyond the signs, the table should be read with care. The coefficients are not causal effects of the covariates on participation, because the model was never specified to estimate those; covariates were included to remove confounding of the treatment-outcome relationship, not to be interpreted individually. A coefficient here is a partial association within a particular specification, and it will move when the specification moves."],

["p", "The standard errors and z statistics carry even less weight than usual. With more than 40,000 observations almost anything is significant, and statistical significance of a coefficient is not a criterion for whether the covariate belongs in the model. A confounder with a z statistic of 1.2 still belongs, because omitting it leaves bias, and dropping covariates on significance grounds is a well-documented way to reintroduce the confounding the model exists to remove. Neither the standard errors nor the p values should be used to select the specification."],

["p", "What the table is genuinely useful for is the sanity check described above, and for noticing surprises. Remoteness carries the largest standardised coefficient of any covariate, which was not obvious in advance, and Section 2.4.1 already flagged remoteness as the covariate whose marginal statistics most understate its role. Seeing it at the top of the model is consistent with that, and is the kind of observation worth a sentence in a methods appendix."],

["h2", "3.5  Six specifications, and what each of them costs"],
["h3", "3.5.1  The comparison"],

["p", "The claim of Section 3.2.2 was that prediction is not the objective. That claim is testable in PLIDA-SIM, because both potential outcomes are recorded and any specification can be scored against the true ATT (i.e., the average treatment effect on the treated, defined in Section 2.3) rather than merely compared with its rivals."],

["p", "We carry six specifications through an identical downstream pipeline: the same 1:1 nearest-neighbour match at a caliper of 0.1 standard deviations on the linear predictor, the same scoring, and the same five independent draws of the data-generating process. The first three add covariate blocks cumulatively; the fourth adds the interactions of Section 3.3.3; the fifth adds the near-instrument; the sixth replaces logistic regression with gradient boosting on the same covariates as the third."],

["frag", [
  "for name, columns, estimator in SPECIFICATIONS:",
  "    ps = fit_propensity(X[columns], D, estimator)",
  "    treated, control, unmatched = match(ps, D, caliper=0.1)",
  "    estimate = (y[treated] - y[control]).mean()",
  "    truth    = tau[treated].mean()          # only because this is simulated",
  "    record(name, auc(D, ps), 100 * (estimate - truth) / truth, unmatched)",
], "Fragment 3.4  Scoring a specification against the truth. Full script: ch03/03_05_specifications.py"],

["p", "The final two lines are the part that no real project can run. Everything above them is ordinary practice and should be run on any dataset; the scoring step requires knowing the answer, and its purpose here is to establish which of the ordinary diagnostics would have pointed at the right specification. The finding is that the one most analysts reach for would not have."],

["tab", "3.3", "Six specifications, ranked by how well they predict treatment.",
  [3000, 1150, 1150, 1150, 1150, 1226],
  ["Specification", "AUC", "Bias", "sd", "Unmatched", "Max weight"],
  [
    ["1  Demographics only", "0.584", "\u221288.4%", "8.0", "0", "2.0"],
    ["2  + location", "0.635", "\u221254.4%", "14.5", "0", "2.8"],
    ["3  + payment and income history", "0.675", "\u221212.5%", "7.6", "2", "4.3"],
    ["4  + interactions", "0.676", "\u22126.5%", "8.4", "2", "4.6"],
    ["5  + near-instrument", "0.728", "\u22123.3%", "3.5", "22", "20.7"],
    ["6  Gradient boosting on set 3", "0.719", "+20.8%", "4.3", "33", "4.6"],
  ],
  "Means across five independent draws. Bias is relative to the true ATT for the matched treated. Unmatched counts treated persons with no control inside the caliper. Max weight is the largest stabilised inverse probability weight the score implies.",
  ["l", "r", "r", "r", "r", "r"]
],

["p", "Read down the AUC column and the specifications improve steadily and then plateau. Read down the bias column and something quite different happens."],
["h3", "3.5.2  What the table shows"],

["p", "The first three rows behave as the theory says they should. Demographics alone recover almost none of the effect, at a bias of \u221288.4 per cent, which is to say the matched estimate is close to zero when the true ATT of the eligible treated persons is $6,408. Adding location improves matters, to \u221254.4 per cent, and adding the payment and income history improves them dramatically, to \u221212.5 per cent. That final block is where the confounding actually lives, and Chapter 2 spent most of its length constructing it."],

["p", "From row 3 onward the two columns part company. Specification 4 raises the AUC by one thousandth and moves the bias by less than its own standard deviation. Specification 5 has the highest AUC in the table and the smallest bias, but it achieves that with a maximum stabilised weight of 20.7 against 4.3 and leaves twenty-two treated persons unmatched against two; Section 3.7 takes it apart. Specification 6 has the second highest AUC and is wrong by +20.8 per cent, in the opposite direction from every other row in the table."],

["p", "The ranking by predictive performance and the ranking by bias therefore agree at the bottom of the table and disagree at the top, which is the worst possible arrangement. A researcher choosing among specifications 3 to 6 on the AUC alone would pick 5 or 6, and 6 is the one specification in the table that is reliably and substantially wrong."],

["p", "One further feature of the table deserves attention, because it is easy to misread. Specification 6 has a smaller draw-to-draw standard deviation than the specification recommended here, at 4.3 against 7.6. A stable estimator is usually a good thing. Here it means the estimate is wrong in the same direction and by the same amount in every draw, so no amount of replication would reveal the problem and a bootstrap would return a narrow interval around the wrong number. Precision and accuracy are different properties, and a diagnostic that measures only the first will prefer specification 6."],

["fig", "3.1", "Prediction against bias, for the six specifications of Table 3.3. (a) All six, with the bias signed rather than absolute and a line at zero. The apparent relationship is produced almost entirely by specifications 1 and 2, which omit the confounders and which no analyst would use. (b) The four specifications a researcher would actually choose between, with bars at one standard deviation across the five draws. Specification 6 has the second highest area under the curve and is the only one on the wrong side of zero. Produced by Script 3.5.",
  "figure_3_1_prediction_against_bias.tif"],

["p", "Figure 3.1 makes the same point twice. Panel (a) plots all six specifications and looks, at a glance, like evidence that better prediction goes with less bias; the impression is produced by specifications 1 and 2, which are in the figure only to show what omitting the confounders does. Panel (b) drops those two and plots the four that a researcher might realistically choose between, with the draw-to-draw spread shown. Within that range there is no relationship between the two axes at all, and the specification with the second highest area under the curve is the only one whose interval excludes zero on the wrong side."],

["h2", "3.6  Machine learning alternatives"],
["h3", "3.6.1  Gradient boosting"],

["p", "There is a substantial literature recommending flexible machine learning methods for propensity score estimation, and the argument for them is a good one. A logistic regression imposes linearity in the log odds, that assumption is almost certainly false in detail, and a method that can discover interactions and non-linearities without being told about them should in principle produce a better balancing score."],

["frag", [
  "from sklearn.ensemble import GradientBoostingClassifier",
  "",
  "gbm = GradientBoostingClassifier(n_estimators=200, max_depth=3,",
  "                                 learning_rate=0.1, random_state=SEED)",
  "analysis[\"ps_gbm\"] = gbm.fit(X, D).predict_proba(X)[:, 1]",
], "Fragment 3.5  A gradient boosted propensity score. Full script: ch03/03_03_estimate_gbm.py"],

["p", "The hyperparameters above are stated rather than tuned, and every boosted number in this chapter comes from them. A reader who reaches instead for causalml, which wraps several boosting libraries behind an interface built for causal work, will get a different score: its defaults fit far more aggressively, and on these data they push the area under the curve to 0.90 and the largest stabilised weight past 100. That is not a criticism of the library. It is a warning that \u201cuse gradient boosting\u201d does not specify a model, and that two defensible defaults can differ more from each other than logistic regression differs from either."],

["frag", [
  "try:                                   # the wrapper, if it will install",
  "    from causalml.propensity import ElasticNetPropensityModel  # noqa",
  "    from causalml.propensity import GradientBoostedPropensityModel",
  "    ps = GradientBoostedPropensityModel().fit_predict(X.values, D)",
  "except ImportError:                    # the fallback, which always will",
  "    ps = GradientBoostingClassifier(**PARAMS).fit(X, D).predict_proba(X)[:, 1]",
], "Fragment 3.6  Two routes to the same boosted score. Full script: ch03/03_03_estimate_gbm.py"],

["p", "Note that the score is fitted and predicted on the same 42,575 rows, without a holdout. This would be indefensible in a prediction task and is the right thing to do here: the score is not being used to forecast anything about unseen persons, it is being used to describe the assignment mechanism for exactly these persons, and a holdout would simply add noise to the quantity we want."],
["h3", "3.6.2  The scores agree, and their consequences do not"],

["p", "The first thing most of us do with two propensity scores is correlate them. On the primary dataset the logistic and boosted scores correlate at 0.904 by Pearson and 0.936 by Spearman, which looks like agreement and is usually reported as reassurance that the choice of estimator did not matter."],

["p", "That is the wrong quantity to look at, and Table 3.4 shows why. Two scores correlating at 0.90 can behave entirely differently in the tails, and the tails are where matching and weighting do their work."],

["tab", "3.4", "The same covariates, two estimators, compared by consequence rather than by agreement.",
  [3100, 1550, 1550, 2626],
  ["", "Logistic", "Gradient boosting", "What it means"],
  [
    ["Area under the ROC curve", "0.670", "0.714", "Boosting predicts better"],
    ["Score range", "0.022 to 0.573", "0.016 to 0.896", "Boosting produces extreme scores"],
    ["Treated above the highest control score", "5", "39", "Persons with no possible match"],
    ["Treated left unmatched at a 0.1 caliper", "2", "33", "The matched sample shrinks"],
    ["Largest stabilised weight", "4.3", "4.6", "Comparable on this measure"],
    ["Bias of the matched estimate", "\u221212.5%", "+20.8%", "Opposite signs, 33 points apart"],
    ["Standard deviation of that bias", "7.6", "4.3", "Boosting is consistently wrong"],
  ],
  "The area under the curve, the score range and the count of treated above the highest control are from the primary dataset, seed 20260808, and come from Script 3.4. The unmatched count, the largest weight, the bias and its standard deviation are means across five draws, from Script 3.5. The two scores correlate at 0.904.",
  ["l", "r", "r", "l"]
],

["p", "The comparison that matters is the last two rows. The two estimators disagree by 33 percentage points on the quantity the analysis exists to produce, they disagree in sign, and the correlation of the scores gave no warning of it. The quantity they disagree about is the ATT, which is what Chapters 5 to 7 all set out to estimate. A chapter framed around whether the scores agree would have concluded that the choice was immaterial."],
["h3", "3.6.3  Why the better predictor is the worse causal model"],

["p", "The explanation is visible in the third and fourth rows of Table 3.4. Boosting achieves its higher AUC by pushing some scores close to 1, and it can do this because trees can isolate small regions of the covariate space in which nearly everyone was treated. Those regions are typically real, in the sense that the persons in them did have a high probability of commencing. They are also exactly the persons for whom no comparable control exists."],

["p", "A propensity score that separates the conditions more sharply therefore buys its predictive performance by destroying common support, which is the condition the whole method depends on. Thirty-three treated persons fall outside the caliper under boosting against two under logistic regression, and the matched sample that remains is systematically different from the treated population: it excludes the persons most likely to be treated, who in these data are also the persons with the largest treatment effects. That is the mechanism producing the +20.8 per cent, and it is the same failure that Chapter 2 traced three times, in which a defensible technical step silently changes which population the estimate describes."],

["p", "None of this is an argument that machine learning has no place in propensity score estimation. It is an argument that the model should be selected on balance and overlap rather than on fit, that a flexible estimator needs to be constrained or trimmed rather than used raw, and that the constraint is the subject of Chapter 4. Readers who intend to use boosting should treat the results in this chapter as a reason to check overlap first rather than a reason to avoid the method."],

["h2", "3.7  What a near-instrument costs"],

["p", "Section 2.4 identified mutual_obligation_status as a near-instrument: a covariate that predicts treatment but has little direct effect on the outcome (i.e., one that is close to an instrument). The standard advice is generally to exclude such covariates, and Chapter 2 undertook that this chapter would quantify what including one costs. Specification 5 of Table 3.3 is that experiment, and the answer is more specific than the usual warning."],

["p", "Including the near-instrument raises the area under the curve from 0.675 to 0.728, the largest gain of any single change in this chapter, which is precisely why the covariate is tempting. Table 3.5 sets out what is purchased with it."],

["tab", "3.5", "The cost of adding the near-instrument to the propensity model.",
  [3300, 1500, 1500, 2526],
  ["", "Without", "With", "Change"],
  [
    ["Area under the ROC curve", "0.675", "0.728", "Improves"],
    ["Largest stabilised weight", "4.3", "20.7", "5 times larger"],
    ["Largest control odds weight", "1.4", "22.3", "16 times larger"],
    ["Effective control sample (odds weights)", "24,247", "3,505", "86 per cent of the controls lost"],
    ["Standard error of the weighted estimate", "368", "475", "29 per cent wider"],
    ["Treated left unmatched at a 0.1 caliper", "2", "22", "More than ten times"],
    ["Bias of the matched estimate", "\u221212.5%", "\u22123.3%", "No reliable change"],
    ["Standard deviation of that bias", "7.6", "3.5", "\u2014"],
  ],
  "Means across five independent draws, eligible population. Effective sample size is the Kish formula applied to the control odds weights, which are the weights the ATT estimator of Chapter 6 uses.",
  ["l", "r", "r", "l"]
],

["p", "The row that settles the question is the effective control sample size. The near-instrument concentrates the weight on a small number of controls, and although all 37,708 of them remain in the file, they carry the information of about 3,500. Six sevenths of the control sample has been spent on a covariate that removes no bias, and it has been spent invisibly, because nothing in the estimator's output reports an effective sample size unless the analyst asks for it."],

["p", "The bias row should be read carefully, because it does not say what the standard warning implies. Including the near-instrument did not make the estimate worse: \u22123.3 per cent against \u221212.5 per cent is nominally better. It is not reliably better, since the standard deviation of the baseline is 7.6 and the two intervals overlap, and it is bought at 29 per cent more standard error and six sevenths of the control information. The accurate statement is that the covariate costs a great deal of precision and buys no dependable reduction in bias, which is the theoretical prediction and is what these data show."],

["p", "The magnitudes are worth recording, because theory predicts the direction of each change and not its size. Measured on v1.1.0 of the dataset, the increase in the largest stabilised weight is about fivefold and the standard error inflation is 29 per cent; the largest control odds weight rises sixteenfold, from 1.4 to 22.3. None of these could have been stated with confidence before the experiment was run, which is a reasonable argument for running it rather than citing the expectation."],

["p", "The general rule that follows is narrower than the usual advice and easier to act on. A covariate should be excluded on near-instrument grounds only when there is a substantive reason to believe it affects treatment and not the outcome, and the reason must come from knowledge of how the programme operates rather than from the data, since the data cannot distinguish a near-instrument from a confounder whose outcome association is mediated. Where the reason is genuinely uncertain, Table 3.5 suggests the safer error: including a true confounder by mistake costs some precision, whereas excluding one leaves bias that no later step recovers."],

["h2", "3.8  Diagnosing the fitted score"],

["p", "Four diagnostics should be run on any fitted propensity score before it is used (i.e., before trimming, matching or weighting), and none of them involves the outcome. They take a few seconds and they are what Chapter 4 acts on."],

["p", "It is worth being explicit about why we exclude the outcome from all four. A diagnostic that uses the outcome can be optimised against, and a specification search that stops when the estimate looks reasonable has produced an estimate that was chosen rather than measured. The discipline of Section 2.6.6, in which the outcome is not touched until Chapter 9, is what makes the diagnostics in this section trustworthy, and it is the single practice most worth carrying into real work."],
["h3", "3.8.1  Range, tails and weights"],

["p", "The first diagnostic is the range of the score in each condition. A score that reaches 1 for some persons would imply an infinite inverse probability weight and no possible comparison; a score that reaches 0 implies the same in the other direction. On the primary dataset the logistic score runs from 0.022 to 0.573, which is comfortable, while the boosted score reaches 0.896, which is not."],

["p", "The second is the weight distribution the score implies, which should usually be examined even by readers who intend to match rather than weight, because a heavy weight tail is a sign of thin overlap whatever the estimator. Reporting the largest weight alone is insufficient; the effective sample size of Table 3.5 is the more informative summary and costs one line."],

["frag", [
  "w = np.where(D == 1, D.mean() / ps, (1 - D.mean()) / (1 - ps))",
  "",
  "print(f\"largest stabilised weight   {w.max():.1f}\")",
  "print(f\"effective control sample    {w[D==0].sum()**2 / (w[D==0]**2).sum():,.0f}\")",
  "print(f\"controls carrying 10pc of weight  {(w[D==0] > np.quantile(w[D==0], .9)).sum():,}\")",
], "Fragment 3.7  Weight diagnostics, which apply whether or not the analysis weights. Full script: ch03/03_06_diagnose_score.py"],
["h3", "3.8.2  Overlap, and what Chapter 4 inherits"],

["tab", "3.6", "Diagnostics for the fitted score, before any trimming.",
  [3000, 1500, 1500, 2926],
  ["Diagnostic", "Logistic", "Boosting", "Reported as"],
  [
    ["Score range", "0.022 to 0.573", "0.016 to 0.896", "1st and 99th percentiles in the DataLab"],
    ["Mean score against observed rate", "0.1143 / 0.1143", "0.1143 / 0.1143", "Agreement is automatic, not a result"],
    ["Largest stabilised weight", "4.2", "4.4", "With the effective sample size beside it"],
    ["Effective control sample (stabilised)", "37,461", "37,465", "Kish formula on the control weights"],
    ["Treated above the highest control score", "5", "39", "Count, never the scores themselves"],
    ["Controls below the lowest treated score", "17", "228", "Count"],
    ["Persons with a score above 0.5", "14", "106", "Count"],
    ["Persons with a score above 0.7", "0", "16", "Count"],
    ["Smallest decile treated cell", "160 of 4,258", "110 of 4,258", "Counts by decile of the score"],
  ],
  "Primary dataset, seed 20260808, eligible population. The two scores use the same covariates and differ only in estimator. The final five rows are what Chapter 4 acts on.",
  ["l", "r", "r", "l"]
],

["p", "The third diagnostic is overlap, which is the share of the score range in which both conditions are represented, and the fourth is the count of persons outside it. Under the logistic score, five treated persons lie above the highest control score and seventeen controls lie below the lowest treated score; fourteen persons in 42,575 have a score above 0.5 and none has one above 0.7. Overlap is therefore good, and the deciles bear that out, with the top decile still containing 3,168 controls against 1,090 treated."],

["p", "Under the boosted score the same counts are 39 and 228, with 106 persons above 0.5 and 16 above 0.7. Two scores fitted to the same covariates on the same 42,575 people therefore hand Chapter 4 substantially different problems, and the difference is a property of the estimator rather than of the data."],

["frag", [
  "tr, ct = ps[D == 1], ps[D == 0]",
  "",
  "print(f\"treated above the highest control  {(tr > ct.max()).sum():,}\")",
  "print(f\"controls below the lowest treated  {(ct < tr.min()).sum():,}\")",
  "print(f\"persons with a score above 0.5     {(ps > 0.5).sum():,}\")",
  "print(pd.crosstab(pd.qcut(ps, 10, labels=False), D))   # the decile table",
], "Fragment 3.8  The four counts Chapter 4 acts on. Full script: ch03/03_06_diagnose_score.py"],

["fig", "3.2", "Overlap under the two estimators. (a) The fitted score by condition under logistic regression, as overlaid histograms on a common axis. (b) The same under gradient boosting, on the same axis, showing the treated mass above the highest control score that the logistic model does not produce. Produced by Script 3.6.",
  "figure_3_2_overlap.tif"],

["p", "This is the practical hand-off. Chapter 4 decides what to do about persons who have no counterpart in the other condition, and the volume of that work is determined here. A reader who follows this chapter with logistic regression will find Chapter 4's trimming makes little difference; a reader who uses boosting will find it essential. Neither reader is wrong, and both should know which situation they are in before they start trimming."],

["box", "In the DataLab: diagnostics that survive disclosure", [
  "Score distributions are usually releasable as histograms with adequate bin counts, and are one of the more useful things to bring out of the environment. Minima and maxima are not: an extreme value of a propensity score can in principle identify the person who holds it, and disclosure rules commonly refuse them.",
  "The practical substitute is to report the first and ninety-ninth percentiles in place of the range, and to report the count of persons outside the common support rather than their scores. Both answer the question that matters and neither identifies anyone.",
]],

["h2", "3.9  Is this score ready to use?"],

["p", "We have produced two scores and a recommendation. The recommendation is specification 3 of Table 3.3, fitted by logistic regression on the eighteen covariates of Table 3.1, with the pure outcome predictor and the near-instrument both held back. That specification is not the best predictor in the table and is the best propensity score in it."],
["h3", "3.9.1  What to record about a propensity score"],

["p", "Six things should be true and documented before a fitted score is carried into Chapter 4. Each corresponds to a decision made somewhere in this chapter."],

["list", [
  "The covariate set was fixed before any model was fitted, and is the set declared in Chapter 2 rather than one selected on model output.",
  "Regularisation is off, or its strength is reported, because shrinkage on a confounder means that confounder is under-adjusted.",
  "The functional form of every continuous covariate is stated, and any transform applied to the outcome scale is distinguished from transforms applied inside the propensity model.",
  "No covariate in the model is measured after treatment began, and none is drawn from a file that exists only for the treated.",
  "The score's range, its weight tail, its effective sample size and the count of persons outside common support are all reported.",
  "The estimator is named, and if a flexible method was used, the overlap diagnostics are reported beside the results rather than after them.",
]],

["p", "None of these is a statistical test and none can be automated. They are what a reviewer will ask for, and they are considerably easier to record while fitting than to reconstruct afterwards."],
["h3", "3.9.2  What this chapter cost"],

["p", "Chapter 2 ended by pricing its preparation decisions against the true effect, and the same accounting is available here. Of the six specifications examined, two are unusable because they omit the confounders, one is reliably wrong by 33 percentage points against the specification that is right, despite predicting better than it, one buys 29 per cent more standard error for no dependable gain, and one adds interactions that move the estimate by less than their own standard deviation."],

["p", "Set against Chapter 2, the comparison is instructive rather than competitive. The worst preparation failure in Chapter 2 cost 55 percentage points of bias; the worst estimation failure here costs 33. Both are large, both are avoidable, and neither would be visible to an analyst who examined only their own output. The difference is that the estimation failure is at least detectable by diagnostics that do not require the outcome, which is why this chapter ends with a checklist and Chapter 2 ended with a caution."],

["p", "There is also a cost that this chapter has not priced, because it falls outside the chapter. Every specification in Table 3.3 was scored after matching, and matching is one of four methods the book goes on to describe. A specification that suits matching may not suit weighting, because the two use the score differently: matching cares about whether a comparable control exists, and weighting cares about the whole shape of the score distribution. Specification 5 illustrates the divergence, being tolerable under matching and severe under weighting, and Chapter 6 revisits it from the weighting side."],
["h3", "3.9.3  Scripts for this chapter"],

["tab", "3.7", "Scripts for Chapter 3. All available from the companion website.",
  [1100, 3400, 3200, 1326],
  ["Script", "File", "Produces", "Runtime"],
  [
    ["3.1", "ch03/03_01_covariate_sets.py", "Table 3.1; the design matrix", "10 s"],
    ["3.2", "ch03/03_02_estimate_logit.py", "Table 3.2; the logistic score", "15 s"],
    ["3.3", "ch03/03_03_estimate_gbm.py", "The boosted score", "30 s"],
    ["3.4", "ch03/03_04_compare_estimators.py", "Table 3.4, primary-dataset rows", "40 s"],
    ["3.5", "ch03/03_05_specifications.py", "Table 3.3; Table 3.4, five-draw rows; Figure 3.1", "4 min"],
    ["3.6", "ch03/03_06_diagnose_score.py", "Table 3.6; Figure 3.2", "20 s"],
    ["3.7", "ch03/03_07_near_instrument.py", "Table 3.5", "3 min"],
  ],
  "Scripts 3.5 and 3.7 generate their own draws, because a single draw cannot separate the differences they report from sampling variability; both ignore --datadir for that reason.",
  ["l", "l", "l", "r"]
],
["h3", "3.9.4  Further reading"],

["p", "Leite (2017, chapter 2) is the closest treatment to this chapter's subject and works through propensity score estimation in R with the same emphasis on specification over fit. Bai and Clark (2019, chapter 2) covers covariate selection and model building with more attention to the assumptions under which the resulting score balances. On the specific question of whether flexible estimators help, the literature is genuinely divided, and a reader forming a view should read at least one paper on each side rather than accepting this chapter's single dataset as settling it."],

["p", "On near-instruments, the result in Section 3.7 is a well-established theoretical prediction that is more often cited than measured, and readers with access to their own data are encouraged to run the equivalent of Table 3.5 before deciding what to include. For the mechanics of gradient boosting as applied to treatment assignment, the causalml documentation is more practical than most published treatments."],
["h3", "3.9.5  Exercises"],

["p", "The exercises use PLIDA-SIM B, the second dataset described in Section 2.9.6, so that answers cannot be carried over from the worked examples above."],

["list", [
  "Fit specification 3 on PLIDA-SIM B and report the score range, the largest stabilised weight and the effective control sample size. State whether overlap is better or worse than in the primary dataset.",
  "Refit specification 3 with education and remoteness entered as sets of dummy variables rather than as ordinal scores. Report the change in the area under the curve and in the fitted scores, and say whether the equal-spacing assumption cost anything detectable.",
  "Turn scikit-learn's default regularisation back on by removing the C argument in Fragment 3.3. Report what happens to the coefficient on prior earnings, and explain why this matters for a confounder in a way it would not matter for a predictor.",
  "Fit the boosted score on PLIDA-SIM B and reproduce the last two rows of Table 3.4. Does the sign of the disagreement between the two estimators hold in the second dataset?",
  "Add occupation_group, the pure outcome predictor, to the propensity model. Report the change in the area under the curve and in the standard error of the matched estimate, and reconcile your answer with Table 2.2.",
]],
["h3", "3.9.6  Study questions"],

["p", "The questions below require no data and are intended to check that the reasoning of the chapter has carried, rather than the mechanics."],

["list", [
  "A propensity model that predicts treatment perfectly is useless. Explain why, in terms of what the score is for rather than in terms of any particular estimator.",
  "Specification 5 has the highest area under the curve in Table 3.3 and the smallest bias. Give two reasons why it is nonetheless not the recommended specification.",
  "The logistic and boosted scores correlate at 0.904 and produce matched estimates 33 percentage points apart. Explain how both facts can be true, and say what this implies about reporting the correlation of two scores as a robustness check.",
  "Specification 6 has the smallest draw-to-draw standard deviation in Table 3.3. Why is that a warning rather than a reassurance?",
  "Deflating the earnings covariates changes the fitted logistic score by nothing at all, while Chapter 2 insisted that deflation matters. Are the two claims in conflict? Explain what deflation does and does not affect.",
  "A colleague drops three covariates from the propensity model because their coefficients are not statistically significant. What is wrong with this procedure, and what should be used to decide instead?",
  "Under one estimator five treated persons lie above the highest control score, and under another thirty-nine do. Both scores were fitted to the same covariates on the same people. What does this tell you about where the choice of estimator does its damage?",
]],

];
